spring.application.name=sentinelai-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:sentinelai}
spring.datasource.username=${POSTGRES_USER:sentinel}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
